aliases:
  - &dir ~/repo
  - &defaults
    working_directory: *dir
    docker:
      - image: circleci/node:lts
  - &cache_key
    key: dependency-cache-{{ checksum "package.json" }}
  - &attach_workspace
    attach_workspace:
       at: *dir

version: 2
jobs:
  checkout_code:
    <<: *defaults
    steps:
      - checkout
      - persist_to_workspace:
          root: *dir
          paths:
            - .

  test:
    <<: *defaults
    steps:
      - *attach_workspace
      - restore_cache: 
          <<: *cache_key
      - run: npm install
      - run: npm test
      - save_cache:
          <<: *cache_key
          paths:
            - ./node_modules
      - persist_to_workspace:
          root: *dir
          paths:
            - node_modules

  release:
    <<: *defaults
    steps:
      - *attach_workspace
      - checkout
      - run: npm run semantic-release

workflows:
  version: 2
  build:
    jobs:
      - checkout_code
      - test:
          requires:
            - checkout_code
      - release:
          context: org-global
          requires:
            - test
